### ISSUE TITLE
Cannot starting mining on RP4

### ISSUE THREAD

**Issue by Ubique88** [jstefanop/Apollo-Miner-Binaries#1]
Hi,

Just got my standard miner, and I have it plugged into a RP4 running Raspberry Pi OS 64bit.

When I am trying to start the miner I am getting the following error;

./apollo-miner: /usr/lib/aarch64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by ./apollo-miner)

Is there anything I am missing?

Thanks

**Comment by jstefanop** [comment]
Try running this and see if it helps

sudo apt-get install --only-upgrade libstdc++6

**Comment by Ubique88** [comment]
Still no joy. 
`libstdc++6 is already the newest version (8.3.0-6).`

Is it worth trying on Ubuntu 64bit for Pi or will it work on Raspberry Pi OS 64bit.?

The Pi I am running on is a fresh install with all updates applied,

**Comment by Ubique88** [comment]
Ok so I think I have figured it out. 
What I ended up doing was adding; `deb http://ftp.de.debian.org/debian sid main` to `/etc/apt/sources.list`
Then ran;
`sudo apt update`
`sudo apt install libstdc++6`
The software now starts and looks for the miner, I just need to turn it on now to check everything is working....But that involves going upstairs to switch it on and currently the football is on, and I have had a beer so maybe at half time.....
