### ISSUE TITLE
Cannot start mining at Pi3b+ linux system

### ISSUE THREAD

**Issue by ucblars** [jstefanop/Apollo-Miner-Binaries#2]
Binarity error

**Comment by ucblars** [comment]
![Screenshot_20210618-212018_RaspController](https://user-images.githubusercontent.com/70774833/122613686-8d9c7180-d085-11eb-9ed6-95e1e938ec55.jpg)

**Comment by Ubique88** [comment]
You need to be using a 64bit OS. Are you running Raspberry Pi OS 64bit?

**Comment by ucblars** [comment]
Thnx! I changed to ubuntu 64 bit version
