### ISSUE TITLE
Incorporate some kind of notification when miner down

### ISSUE THREAD

**Issue by gurkburk76** [jstefanop/Apollo-Miner-Binaries#5]
I'de love to get a pushover notice when/if the miner for some reason stops working or similar, email would be lesser choice but posssibly quick and easy for the author to incorporate.

Also. better documentation doing --help shows a lot of options but no in-depth explanation to what they do :)

**Comment by jstefanop** [comment]
Download the latest binaries, most of the miner failing issues have been fixed
